name: undone
version: 0.0.1-dev
description: A little undo-redo library.  Not a song about sweaters.
author: Ross Smith <ross.dart.lang@gmail.com>
dependencies:
  browser: '>=0.4.1 <1.0.0'
  unittest: '>=0.4.1 <1.0.0'
